spring:
  datasource:
    url: jdbc:mysql://mysql:3306/recipe-db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    
spring.datasource.initialization-mode: always